apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-service
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx    
spec:
  rules:  
    - http:
        paths:
        - backend:
            serviceName: prometheus-server
            servicePort: 9090
          path: /